version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wernetech_admin
      POSTGRES_PASSWORD: admin_9876
      POSTGRES_DB: empresa
    volumes:
      - pgdata:/bitnami/postgresql

  app:
    build: .
    container_name: wernetech_app
    restart: always
    ports:
      - "3000:3000" # Next.js
      - "3333:3333" # NestJS
      - "4000:4000" # Seu backend Express
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://wernetech_admin:admin_9876@postgres:5432/empresa"
      JWT_SECRET: "2fb7b9dc6cf44c0a928b0e9f41f3c9286bb35fef7d1a411c6c88b85b6e007c78"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
