version: "3.8"

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wernetech_admin
      POSTGRES_PASSWORD: admin_9876
      POSTGRES_DB: empresa
    volumes:
      - pgdata:/bitnami/postgresql

  backend:
    build: ./backend
    container_name: wernetech_backend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://wernetech_admin:admin_9876@postgres:5432/empresa"
      JWT_SECRET: "2fb7b9dc6cf44c0a928b0e9f41f3c9286bb35fef7d1a411c6c88b85b6e007c78"
      PORT: 4000
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: quaresma.davi@gmail.com
      SMTP_PASS: aeymdihomjbpvvxv

  frontend:
    build: ./frontend
    container_name: wernetech_frontend
    restart: always
    ports:
      - "3002:3000"
    environment:
      NEXT_PUBLIC_API: http://localhost:4000
    depends_on:
      - backend

volumes:
  pgdata:
